# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    # Look for `requirements.txt` file in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
    groups:
      - "all-pip-dependencies":
          patterns:
            - "*"
          update-types:
            - "version-update:semver-patch"
            - "version-update:semver-minor"
          commit-message:
            prefix: "deps(pip):"
            include-scope: true
